add sizing design tokens
Vonage/vivid-design-tokens-properties pull request #21
Opened 2021-11-28 12:02 UTC by rinaok

2021-11-29 06:34 UTC, YonatanKra requested changes
Additionally to the two comments, could you please add tests like the shadow tests?
There are tests both for the parser and the global scripts.

2021-11-29 06:34 UTC, YonatanKra commented on globals/sizing/consts.js
> +export const properties = ['xxxs', 'xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'].map(val => `${val}`);
There's no need for mapping if you return the same value.

2021-11-29 06:34 UTC, YonatanKra commented on globals/sizing/consts.js
> +export const subItems = ['4px-scale', '8px-scale'].map(val => `${val}`);
Same comment as below for no need for mapping.

2021-11-29 10:43 UTC, rachelbt commented on scripts/figma-parsers/parsers/sizing-figma-data-parser.js
> +        'xxxs': 'xxxs',
I think we should consider using xs, 2xs, 3xs, xl, 2xl, 3xl ext.to avoid spelling and make it more readable

2021-11-29 10:43 UTC, rachelbt reviewed
I think we should consider using xs, 2xs, 3xs, xl, 2xl, 3xl ext.to avoid spelling and make it more readable

2021-11-29 12:23 UTC, YonatanKra commented
> I think we should consider using xs, 2xs, 3xs, xl, 2xl, 3xl ext.to avoid spelling and make it more readable

Sounds reasonable. @rachelbt do you have any examples of libraries that use either convention?

2021-11-29 12:32 UTC, rachelbt commented
> > I think we should consider using xs, 2xs, 3xs, xl, 2xl, 3xl ext.to avoid spelling and make it more readable
> 
> Sounds reasonable. @rachelbt do you have any examples of libraries that use either convention?

Its usually in use for fonts, but not only:

- https://uniformcss.com/cheatsheet/font-sizes/
- https://windicss.org/utilities/sizing.html
- https://tailwindcss.com/docs/max-width

2021-11-29 12:55 UTC, YonatanKra commented
> > > I think we should consider using xs, 2xs, 3xs, xl, 2xl, 3xl ext.to avoid spelling and make it more readable
> > 
> > Sounds reasonable. @rachelbt do you have any examples of libraries that use either convention?
> 
> Its usually in use for fonts, but not only:
> 
> - https://uniformcss.com/cheatsheet/font-sizes/
> - https://windicss.org/utilities/sizing.html
> - https://tailwindcss.com/docs/max-width
> 

Oh no!!! Now that you said `tailwind` is doing it @yinonov will never agree 😉

2021-11-29 14:36 UTC, yinonov commented
predefining by size units will result in the following interface

```html
<vwc-icon size="3xs" ...
```

unless we map each component to its 3 preferred values 
e.g. icon size could map -
- small = 3xs
- medium = xl
- large = 2xl

alternatively we can refine the naming above to a readable version have a "wild" interface
e.g. icon size picks types and reacts only to that pick -
- 3xs
- xl
- 2xl

2021-11-29 15:56 UTC, rinaok commented
> Additionally to the two comments, could you please add tests like the shadow tests? There are tests both for the parser and the global scripts.

Added tests and changed the sizes to xs, 2xs, 3xs, xl, 2xl, 3xl

2021-11-30 10:16 UTC, jshenkman commented
> predefining by size units will result in the following interface
> 
> ```
> <vwc-icon size="3xs" ...
> ```
> 
> unless we map each component to its 3 preferred values e.g. icon size could map -
> 
> * small (3xs)
> * medium (xl)
> * large (2xl)
> 
> alternatively we can refine the naming above to a readable version have a "wild" interface e.g. icon size picks types and reacts only to that pick -
> 
> * 3xs
> * xl
> * 2xl

I think mapping each component to its 3 sizes actually makes sense. "Hiding" the values themself and just giving the scale.
Kinda similar to color token we hide the hardcoded values under connotation, so the user knows what information he wants to show but doesn't care what shade of purple is the CTA one. Same with button size, the user needs the smallest one so he will choose small, he doesn't need to care/know that it's 32px hight

2021-11-30 10:17 UTC, jshenkman commented
> > Additionally to the two comments, could you please add tests like the shadow tests? There are tests both for the parser and the global scripts.
> 
> Added tests and changed the sizes to xs, 2xs, 3xs, xl, 2xl, 3xl

I'm happy with this naming! Updated also in Figma file

2021-11-30 10:45 UTC, yinonov commented
> tton size, the user needs the smallest one so he will choose small, he doesn't need to care/know that it's 32px hight

so last question - hypothetically textfield 'small' can be different than button 'small'. is that an ok way to go (ui-wise)?

2021-11-30 11:17 UTC, jshenkman commented
> > tton size, the user needs the smallest one so he will choose small, he doesn't need to care/know that it's 32px hight
> 
> so last question - hypothetically textfield 'small' can be different than button 'small'. is that an ok way to go (ui-wise)?

Umm good Q, but it's pretty much the same today using sizing names - dense, default, and enlarged. 
Today we have 48px text field which is default and then 40px which is dense as opposed to the button which is dense 32 default 40 and enlarged 48... so even now it's confusing for the user, he will want a default button and default text field and get different sizes...

2021-11-30 14:49 UTC, YonatanKra commented on test/sizing/sizing.spec.js
> +            it(`should write to JSON`, function () {
`should write to JSON only once`

2021-12-01 13:00 UTC, YonatanKra commented on test/sizing/sizing.spec.js
> +            it(`should write to JSON once`, function () {
`should write to JSON only once` and make sure the mockWriteJSON is called only once.
`mockWriteJson = jest.fn(mockWriteJson);`
And then when you want to check, do this:
`expect(mockJsonWrite.mock.calls).toHaveLength(1);`
Look at the `color.spec` to see an example.

2021-12-01 15:40 UTC, YonatanKra commented on test/sizing/sizing.spec.js
> +                mockWriteJson = jest.fn(mockWriteJson);
Do this at the top. Something like:
```
beforeEach(function() {
  results.length = 0;
  mockWriteJson = jest.fn(function(data, path) {
    results.push({
      data, path
    });
});
```

2021-12-02 06:17 UTC, YonatanKra commented on test/sizing/sizing.spec.js
> +            });
Aren't these two do the same?

2021-12-02 09:14 UTC, YonatanKra approved these changes

2021-12-02 09:24 UTC, merged